### ISSUE TITLE
rnaseq-cgl gets only No log file present errors

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/toil-scripts#438] opened 2016-09-07 17:17 UTC
```
toil (3.3.0)
toil-scripts (2.0.9)
```

This is production run https://github.com/BD2KGenomics/core-operations/issues/77

The inputs have been downloaded from SRA (I think) and are not recent. Many of the files are small, indicating low read coverage. You can see them [on s3](https://s3-us-west-2.amazonaws.com/cgl-driver-projects-encrypted/ckcc-stanford/ckcc_issue77_input/)

Note that the files are from two different sources. The `SRR` files largely came through, except for `SRR787350` which had a `cutadapt` error. However, the other samples (`7316-<>-RNA`) nearly all failed but the pipeline throws no errors. Instead there are  30 `No log file is present, despite jobWrapper failing` warnings.

[ckcc77_log.txt](https://github.com/BD2KGenomics/toil-scripts/files/459842/ckcc77_log.txt)
[ckcc77_config.txt](https://github.com/BD2KGenomics/toil-scripts/files/459843/ckcc77_config.txt)
[ckcc77_manifest.txt](https://github.com/BD2KGenomics/toil-scripts/files/459850/ckcc77_manifest.txt)

**Comment by jvivian** [comment] 2016-09-07 17:39
If the workers are still up, can you check the mesos logs on the worker?  You can find the stderr or stdout logs by typing:

```
find -name "std*" /var/lib/mesos/
```

Otherwise, I can only suggest running it with `--restart` to see if the error messages show up.  On EC2, did the nodes fail any "status checks"?  Were the workers c3.8xlarge?  If you rerun the failed samples and don't get output logs, then we'll need to open a Toil issue. 

Alternatively, running one of the failed samples in single machine could determine why all those samples failed and let me know if there's an issue with the pipeline.

**Comment by adurbin2** [comment] 2016-09-07 18:10
I've asked Holly to llok at the incoming files from a QC viewpoint. We are very interested in these 31 samples to enrich/improve the TumorMap reference set... they were not easy to obtain, and anything that can be done to make them more usable would be extremely helpful.

**Comment by jvivian** [comment] 2016-09-07 18:23
@adurbin2 — The log from running one of the samples locally should let me ascertain why the sample failed, and is probably the reason for that group failing.

**Comment by adurbin2** [comment] 2016-09-07 18:41
Is that something Rob can do (as he did for the prospective subjects in batch 73) or is it something to be done by Core folk? Holly will not have bandwidth on this for at least a day or so; although she had taken a preliminary look at the files on their way in & thought they looked OK.

**Comment by Jeltje** [comment] 2016-09-08 17:36
Yikes, for some reason I don't get emails on these tickets, sorry I didn't respond. The workers were killed off by your monitor script @jvivian :-) So no luck there - equally on the status checks. They were c3.8xlarge. I did notice that the run script ran through the samples really quickly (the workers all remained up) and only slowed down when it got to the `SRR` samples. Something decided right off the bat these were not going to be run.

I agree that running on a single sample (maybe locally) would provide more info, but I don't have the bandwidth to debug this right now. @adurbin2 it would certainly help if Rob could run one and save the logs. Any of the `7316-155-RNA` samples will do, except `7316-155-RNA_406957` (it passed).

**Comment by adurbin2** [comment] 2016-09-08 21:08
I understand Rob is working on this in the next few days --

**Comment by rcurrie** [comment] 2016-09-09 04:30
I'll run on a single machine tomorrow and see if the log output has any hints and report back.

**Comment by rcurrie** [comment] 2016-09-09 15:51
@Jeltje I'm running 7316-1057-RNA_401550_R1/R2.fq.gz, its one that Holly took a look at visually and didn't see anything obviously wrong. Want to make sure that it is one that DID fail.

**Comment by Jeltje** [comment] 2016-09-09 16:55
That's correct, 7316-1057-RNA_401550 failed.

**Comment by rcurrie** [comment] 2016-09-09 17:59
So far its running fine (in STAR) with no errors. On this machine it typically takes 6-8 hours to run so thought I'd mention as it sounded like these failed fast in the core. If this completes fine then its likely something in the distributed world.

**Comment by Jeltje** [comment] 2016-09-09 18:24
I will redo a few samples of the original run to verify that.

**Comment by Jeltje** [comment] 2016-09-09 19:46
So far, so good. I will let these finish and report back.

**Comment by rcurrie** [comment] 2016-09-09 20:18
Still running with no issues (rsem-run)

**Comment by rcurrie** [comment] 2016-09-09 23:40
7316-1057-RNA_401550 finished fine on my machine - no errors.

**Comment by Jeltje** [comment] 2016-09-10 00:54
Thanks Rob! Of my three test samples, one (can't tell which one) failed on rsem, and only one of my three worker nodes is doing anything, so I'm assuming that one of the remaining two samples has disappeared.

I've copied the stderr logs off the idle workers (the stdouts were empty) but nothing jumps out.

[w1_stderr.txt](https://github.com/BD2KGenomics/toil-scripts/files/465134/w1_stderr.txt)
[w3_stderr.txt](https://github.com/BD2KGenomics/toil-scripts/files/465135/w3_stderr.txt)

I will let this finish and add the master log when done.

**Comment by rcurrie** [comment] 2016-09-10 04:57
Possible Aha - I just looked at the very top of this thread and see its toil 2.0.9. I"m using the 2.0.8 docker. Any idea what version of the toil script was used for the last run/batch that worked? If it was 2.0.8 then we can look at the git diffs. The latest version on quay is 2.0.8--1.10.3--513d7eff7...
@jvivian if its easy and you kick off a 2.0.9 based docker built I'll re-run the sample that passed today as an A/B.

**Comment by Jeltje** [comment] 2016-09-10 18:53
Good catch Rob! 

It looks like two of the three jobs ran fine - I have `.bam`, `.bigwig`, and `.tar.gz` output for them. For the remaining one, `7316-942-RNA_400855` the `.tar.gz` is missing. This appears to be due to a rather cryptic error in the rsem workflow:

``` 
samtools sort -@ 32 -m 1G rsem.transcript.bam rsem.transcript.sorted
ip-172-31-22-26: 2016-09-10 00:28:11,114 WARNING: toil.leader: e290bb24-3df1-4c93-a13c-21ba065769ff:    [bam_sort_core] merging from 160 files...
ip-172-31-22-26: 2016-09-10 00:28:11,115 WARNING: toil.leader: e290bb24-3df1-4c93-a13c-21ba065769ff:    "samtools sort -@ 32 -m 1G rsem.transcript.bam rsem.transcript.sorted" failed! Plase check if you provide correct parameters/options for the pipeline!
```

[test77log.txt](https://github.com/BD2KGenomics/toil-scripts/files/465577/test77log.txt)
Interestingly, the file ended with `The job store 'aws:us-west-2:jeltje-rnaseq-ckcc77' contains 7 failed jobs`

But at least the jobs stopped disappearing! So I'll restart the rest and maybe @jvivian can help out with that samtools error.

For completeness, the worker logs:
Interestingly, the stdout file contains the errors, while stderr contains the run log.
[w2.stderr.txt](https://github.com/BD2KGenomics/toil-scripts/files/465578/w2.stderr.txt)
[w2.stdout.txt](https://github.com/BD2KGenomics/toil-scripts/files/465579/w2.stdout.txt)

**Comment by jvivian** [comment] 2016-09-12 16:56
Can't help with that RSEM error, never seen it before.

**Comment by jvivian** [comment] 2016-09-12 17:10
> Possible Aha - I just looked at the very top of this thread and see its toil 2.0.9. I"m using the 2.0.8 docker. Any idea what version of the toil script was used for the last run/batch that worked? If it was 2.0.8 then we can look at the git diffs. The latest version on quay is 2.0.8--1.10.3--513d7eff7...
@jvivian if its easy and you kick off a 2.0.9 based docker built I'll re-run the sample that passed today as an A/B.

@rcurrie — The difference between toil-scripts 2.0.8 and 2.0.9 is a bugfix to a different pipeline.  We're going to be splitting up the pipelines into separate repositories so the versioning makes more sense.

**Comment by Jeltje** [comment] 2016-09-12 17:42
Restarted run; included the test sample that failed with the `rsem/samtools` error

**Comment by Jeltje** [comment] 2016-09-13 21:49
I just started another run (`toil-scripts 2.0.10`) and within minutes I got 28 `WARNING: toil.leader: No log file is present, despite jobWrapper failing` errors. That doesn't seem right.

**Comment by jvivian** [comment] 2017-01-20 00:02
Closing. Reopen if it can be reproduced.

**Closed by jvivian** 2017-01-20 00:02 UTC
Labels: need info
