### ISSUE TITLE
toil-rnaseq re-run STAR with at least --limitBAMsortRAM fails

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/toil-scripts#467] opened 2016-10-02 23:02 UTC
`toil-scripts 2.0.10` on `c3.8xlarge`

It looks like the program sees that it has memory problems and tries to rerun, but deletes some necessary input files, leading to a fatal error:

```
        EXITING because of fatal ERROR: not enough memory for BAM sorting:
        SOLUTION: re-run STAR with at least --limitBAMsortRAM 32019472857
        Oct 02 19:00:00 ...... FATAL ERROR, exiting
        INFO:toil.fileStore:CACHE: Added file with ID '343fec70-3060-4427-ad20-33f20ba1f56a' to the cache.
        INFO:toil.fileStore:CACHE: Added file with ID '084e04ee-b6c7-42e6-a27d-24cb3cd98767' to the cache.
        INFO:toil.fileStore:LOG-TO-MASTER: Successfully deleted local copies of file with ID '343fec70-3060-4427-ad20-33f20ba1f56a'.
        INFO:toil.fileStore:LOG-TO-MASTER: Successfully deleted local copies of file with ID 'aa31152a-c0a8-4114-bf02-5689d6877987'.
        INFO:toil.fileStore:LOG-TO-MASTER: Successfully deleted local copies of file with ID '6a439834-018f-4f86-a9ea-9f9448979c45'.
        INFO:toil.fileStore:LOG-TO-MASTER: Successfully deleted local copies of file with ID '084e04ee-b6c7-42e6-a27d-24cb3cd98767'.
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 330, in main
            job._runner(jobWrapper=jobWrapper, jobStore=jobStore, fileStore=fileStore)
          File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1043, in _runner
            returnValues = self._run(jobWrapper, fileStore)
          File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 991, in _run
            return self.run(fileStore)
          File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1136, in run
            rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
          File "/tmp/pip-build-1z5rba/toil-scripts/toil_scripts/tools/aligners.py", line 64, in run_star
          File "/usr/local/lib/python2.7/dist-packages/toil/fileStore.py", line 222, in writeGlobalFile
            fileHandle = open(absLocalFileName, 'r')
        IOError: [Errno 2] No such file or directory: '/var/lib/toil/toil-e2c3076c-7c07-474c-90be-971ff7126e78/tmpQN4H9r/72684e5f-1962-48cc-a2ea-335b01645bf4/tFePrnS/rnaSignal.UniqueMultiple.str1.out.bg'
```

This happens 4 times on different samples (I ran without `--retry`):
[full log](http://hgwdev.cse.ucsc.edu/~jeltje/toil/limitBAMsortRAM.err)

**Comment by Jeltje** [comment] 2016-10-02 23:04
Weirdly, though I cannot say exactly which samples caused this, none of the seven failed samples from this run has input fastqs bigger than 5.8G.

**Comment by jvivian** [comment] 2016-10-02 23:19
Can you post the `cat /proc/meminfo` ?  It seems absurd that we've never encountered this error before  with samples much larger. I checked and amazon didn't mysteriously lower the amount of RAM assigned to c3.8xlarge or anything. 

The resource requirements for this job are all the cores on the machine and 40G of RAM. STAR is saying it needed ~29.0GiB which should definitely be available on a system with 60GiB.

Any chance you noticed or caught if multiple jobs were running concurrently on one node?

**Comment by Jeltje** [comment] 2016-10-03 05:34
I don't know which machine it happened on. `cat /proc/meminfo` on a random worker gives `MemTotal:       61837040 kB` so that should be fine.
I will rerun the five problem samples tomorrow to see if it happens again. I'm running with `--maxCores 4` but I don't know if that means there can be multiple jobs on a machine. How do I check that?

**Comment by jvivian** [comment] 2016-10-03 17:23
I was going to ask if there was a chance you were running with `maxCores` ... 

That will definitely do it. It doesn't make sense to run the pipeline with a cores restriction on c3.8xlarge. In this case, other jobs that usually reserve 16 or 32 cores are being colocated on the same node, stealing memory from STAR.

**Comment by Jeltje** [comment] 2016-10-03 18:24
Correction, I'm running with `--defaultCores 4`. Does that change the answer?

**Comment by hannes-ucsc** [comment] 2016-10-03 20:34
Thank you for this bug report. Do you think it is possible to reproduce this with an individual sample?

**Comment by jvivian** [comment] 2016-10-03 21:00
> Correction, I'm running with --defaultCores 4. Does that change the answer?

Yup, makes the problem more interesting ;)  As Hannes said, any chance you have the bandwidth to just run STAR on your largest sample? If you can reproduce the error with a single sample, it means we can ideally fix it with the `--limitBam..` option. If not, then something more insidious is going on.

**Comment by Jeltje** [comment] 2016-10-03 21:05
I will try that later today, once I get back to work.

**Comment by Jeltje** [comment] 2016-10-04 00:13
@jvivian what is the star command? The docker image doesn't give a usage statement and the `run_star` module in aligners.py is not completely clear to me. For instance, what *is* `str(cores)` here? 32?

**Comment by Jeltje** [comment] 2016-10-04 03:02
Bingo! It happened on a c3.8xlarge worker all by itself.
Command:

` docker run -v /mnt/ephemeral/var/lib/toil/workdir:/data $star $params $seqs
docker run -v /mnt/ephemeral/var/lib/toil/workdir:/data quay.io/ucsc_cgl/star:2.4.2a--bcbd5122b69ff6ac4ef61958e47bde94001cfe80 --runThreadN 32 --genomeDir /data/starIndex --outFileNamePrefix rna --outSAMtype BAM SortedByCoordinate --outSAMunmapped Within --quantMode TranscriptomeSAM --outSAMattributes NH HI AS NM MD --outFilterType BySJout --outFilterMultimapNmax 20 --outFilterMismatchNmax 999 --outFilterMismatchNoverReadLmax 0.04 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --sjdbScore 1 --outWigType bedGraph --outWigStrand Unstranded --outWigReferencesPrefix chr --readFilesIn /data/R1.fastq /data/R2.fastq`

Log:
```
Oct 04 00:49:44 ..... Started STAR run
Oct 04 00:49:44 ..... Loading genome
Oct 04 00:50:14 ..... Started mapping
Oct 04 01:03:35 ..... Started sorting BAM

EXITING because of fatal ERROR: not enough memory for BAM sorting:
SOLUTION: re-run STAR with at least --limitBAMsortRAM 31321057204
Oct 04 01:03:35 ...... FATAL ERROR, exiting

```
```
/proc/meminfo
MemTotal:       61837040 kB
```

**Comment by Jeltje** [comment] 2016-10-04 03:04
I have stopped the toil box in case you want to do something else, let me know when it's OK to delete.

**Comment by jvivian** [comment] 2016-10-04 04:15
Excellent! Thanks for reproducing =) Can you rerun with --limitBAMsortRAM
42950000000
​

On Mon, Oct 3, 2016 at 8:04 PM Jeltje <notifications@github.com> wrote:

I have stopped the toil box in case you want to do something else, let me
know when it's OK to delete.

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/BD2KGenomics/toil-scripts/issues/467#issuecomment-251284255>,
or mute the thread

**Comment by Jeltje** [comment] 2016-10-04 18:24
That worked! Now how do I pass that on into the workflow? Other than hacking the python code, of course...

**Comment by jvivian** [comment] 2016-10-04 18:27
We're including in this imminent PR! Going out after scrum. Thanks for
testing this jeltje, very helpful!

**Comment by Jeltje** [comment] 2016-10-05 17:06
Not done yet...! 
This time about half of the remaining 22 samples made it. I've split up the error logs to make sense of them; I ran with `--retryCount 2` so most errors occur three times... in a way.

Despite setting the disk size to 35G (largest file 33G), two of the samples (not sure which) still died with `not enough memory for BAM sorting` (log files [3](http://hgwdev.cse.ucsc.edu/~jeltje/toil/log.3), [6](http://hgwdev.cse.ucsc.edu/~jeltje/toil/log.6), [7](http://hgwdev.cse.ucsc.edu/~jeltje/toil/log.7) ,[9](http://hgwdev.cse.ucsc.edu/~jeltje/toil/log.9), [12](http://hgwdev.cse.ucsc.edu/~jeltje/toil/log.12) and [14](http://hgwdev.cse.ucsc.edu/~jeltje/toil/log.14))

Two jobs `core dumped` after an `invalid BAM binary header` error (log [10](http://hgwdev.cse.ucsc.edu/~jeltje/toil/log.10) and [13](http://hgwdev.cse.ucsc.edu/~jeltje/toil/log.13))

[log11](http://hgwdev.cse.ucsc.edu/~jeltje/toil/log.11) shows a ` ERROR: number of bytes expected from the BAM bin does not agree with the actual size on disk: 11373803225   7496024064   16`
And then a 'cachelock' eror follows.

I wonder if this fills up the drive for other jobs, because logs [8](http://hgwdev.cse.ucsc.edu/~jeltje/toil/log.8), [15](http://hgwdev.cse.ucsc.edu/~jeltje/toil/log.15), [16](http://hgwdev.cse.ucsc.edu/~jeltje/toil/log.16) get `StorageDataError: BotoClientError: Out of space for destination file`  and logs [4](http://hgwdev.cse.ucsc.edu/~jeltje/toil/log.4) and [5](http://hgwdev.cse.ucsc.edu/~jeltje/toil/log.5) get `gzip: no space left on device`

Tagging @hannes-ucsc because this is probably related to https://github.com/BD2KGenomics/toil/issues/1154

**Comment by Jeltje** [comment] 2016-10-05 17:14
The failed samples are all tar files that range in size between 23 G and 32 G.

**Comment by hannes-ucsc** [comment] 2016-10-05 17:45
Looking into it now.

> Tagging @hannes-ucsc because this is probably related to BD2KGenomics/toil#1154

Issue  BD2KGenomics/toil#1154 is about workflow directories being left over *after* a run ends. So let me ask you again. 1) Did you run with `--workDir=/var/lib/toil`? 2) Did you see anything in `/var/lib/toil` on any worker after `toil-rnaseq` exited? If the answer to 2 is "I don't know" or "yes" and you started another or the same workflow again on the same workers, it is possible that the left over work dirs from a previous run contribute to the problem. 

Log 7 is a bad link.

**Comment by hannes-ucsc** [comment] 2016-10-05 18:02
log.3 is from a protect

Many of the links are broken.

**Comment by Jeltje** [comment] 2016-10-05 18:25
Hold on, all log links were wrong. Fixed.

**Comment by jvivian** [comment] 2016-12-13 08:49
Issue was resolved by using the proper instance size.

**Closed by jvivian** 2016-12-13 08:49 UTC
