### ISSUE TITLE
Support ICGC Storage System on S3/Ceph in Workflows

### ISSUE THREAD

**Issue by briandoconnor** [BD2KGenomics/toil-scripts#218] opened 2016-03-31 00:09 UTC
@jvivian this is a longer term goal, if we go with the ICGC storage system we want to make sure workflow inputs/outputs can use this system.

Assigning to Hannes so he can reassign

**Comment by briandoconnor** [comment] 2016-03-31 00:10
Does this belong in https://github.com/BD2KGenomics/core-operations/issues instead?

**Comment by hannes-ucsc** [comment] 2016-03-31 00:18
Nope, this is the correct project, @briandoconnor.

**Comment by jvivian** [comment] 2016-05-18 20:10
Duplicate of #266

**Closed** 2016-05-18 20:11 UTC
Labels: enhancement
