### ISSUE TITLE
Curl called on S3 URL in exome pipeline

### ISSUE THREAD

**Issue by JakeNarkizian** [BD2KGenomics/toil-scripts#364] opened 2016-07-16 23:21 UTC
[log.txt](https://github.com/BD2KGenomics/toil-scripts/files/367591/log.txt)
log is too long to post here. See attached script generated text file.

**Comment by jvivian** [comment] 2016-07-18 17:06
Headers are being invoked, meaning this is an identical issue to: https://github.com/BD2KGenomics/toil-scripts/issues/361

**Comment by hannes-ucsc** [comment] 2016-07-18 17:31
@jvivian, If the issue is systemic to toi-scripts, track this as a single issue and close this one as a duplicate.

**Comment by jvivian** [comment] 2016-07-18 17:43
Duplicate of #361

**Closed by jvivian** 2016-07-18 17:43 UTC
Labels: bug
