### ISSUE TITLE
OSError reported by bwa_alignment.py toil script

### ISSUE THREAD

**Issue by jpdna** [BD2KGenomics/toil-scripts#106] opened 2016-02-17 21:01 UTC
We are trying to run:

```
https://github.com/fnothaft/toil-scripts/blob/adam-vs-gatk-heuermh/src/toil_scripts/adam_gatk_pipeline/call_vs_grch38.sh
```
on a cluster created as so:

```
cgcloud create-cluster --zone us-west-2a --cluster-name justin-adam-gatk --num-workers 2 --instance-type r3.8xlarge --ebs-volume-size 100 toil
```

and specifically, I changed toil invocation command line in call_vs_grch38.sh  to use a  larger test file input fastq at:

```
--s3_bucket s3://paschall-fc-test-west-2 
--uuid out_chr_22
```

The relevant error reported when running the toil script is below,
and the larger output at:  http://pastebin.com/XP8wkBHk

The line of code causing the exception is in the bwa_alignment_code.py that I think John V wrote originally - so good to see if you have seen this before.  bwa does run for a while before this exception occurs.

Error reported here:

```
https://github.com/fnothaft/toil-scripts/blob/adam-vs-gatk-heuermh/src/toil_scripts/batch_alignment/bwa_alignment.py#L462
```

```
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	WARNING:toil_scripts.batch_alignment.bwa_alignment:Calling docker with docker run --rm --log-driver=none -v /var/lib/toil/tmp0Z8f8R/localTempDir/t_O317i:/data.
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	WARNING:toil_scripts.batch_alignment.bwa_alignment:Calling docker with docker run --rm --log-driver=none -v /var/lib/toil/tmp0Z8f8R/localTempDir/t_O317i:/data.
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	Calling docker with docker run --rm --log-driver=none -v /var/lib/toil/tmp0Z8f8R/localTempDir/t_O317i:/data
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	WARNING: many programs require read groups. Please specify with -R if you can.
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	[W::stk_mergepe] the 2nd file has fewer records.
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	Traceback (most recent call last):
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	  File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 283, in main
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	    fileStore=fileStore)
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1294, in _execute
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	    returnValues = self.run(fileStore)
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1400, in run
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	  File "toil_scripts/batch_alignment/bwa_alignment.py", line 462, in fix_bam_header
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 652, in readGlobalFile
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	    os.link(cachedAbsFilePath, userPath)
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	OSError: [Errno 1] Operation not permitted
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	Exiting the worker because of a failed jobWrapper on host ip-172-31-28-134
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host ip-172-31-28-134
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job a3b60d83-825c-4e6d-9d41-6a76f2356d12 to 3
INFO:toil.batchSystems.mesos.batchSystem:Preparing to launch Mesos task 15 using offer 2e1d557f-bae2-4d81-8a02-b72a4092d5b8-O368...
INFO:toil.batchSystems.mesos.batchSystem:...launching Mesos task 15
WARNING:toil.leader:The jobWrapper seems to have left a log file, indicating failure: a3b60d83-825c-4e6d-9d41-6a76f2356d12
WARNING:toil.leader:Reporting file: a3b60d83-825c-4e6d-9d41-6a76f2356d12
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	WARNING:toil_scripts.batch_alignment.bwa_alignment:Calling docker with docker run --rm --log-driver=none -v /var/lib/toil/tmpdQaF2c/localTempDir/tN0SWmL:/data.
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	WARNING:toil_scripts.batch_alignment.bwa_alignment:Calling docker with docker run --rm --log-driver=none -v /var/lib/toil/tmpdQaF2c/localTempDir/tN0SWmL:/data.
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	Calling docker with docker run --rm --log-driver=none -v /var/lib/toil/tmpdQaF2c/localTempDir/tN0SWmL:/data
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	WARNING: many programs require read groups. Please specify with -R if you can.
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	[W::stk_mergepe] the 2nd file has fewer records.
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	Traceback (most recent call last):
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	  File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 283, in main
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	    fileStore=fileStore)
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1294, in _execute
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	    returnValues = self.run(fileStore)
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1400, in run
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	  File "toil_scripts/batch_alignment/bwa_alignment.py", line 462, in fix_bam_header
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 652, in readGlobalFile
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	    os.link(cachedAbsFilePath, userPath)
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	OSError: [Errno 1] Operation not permitted
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	Exiting the worker because of a failed jobWrapper on host ip-172-31-28-135
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host ip-172-31-28-135
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job a3b60d83-825c-4e6d-9d41-6a76f2356d12 to 2
INFO:toil.batchSystems.mesos.batchSystem:Preparing to launch Mesos task 16 using offer 2e1d557f-bae2-4d81-8a02-b72a4092d5b8-O575...
INFO:toil.batchSystems.mesos.batchSystem:...launching Mesos task 16
WARNING:toil.leader:The jobWrapper seems to have left a log file, indicating failure: a3b60d83-825c-4e6d-9d41-6a76f2356d12
WARNING:toil.leader:Reporting file: a3b60d83-825c-4e6d-9d41-6a76f2356d12
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	WARNING:toil_scripts.batch_alignment.bwa_alignment:Calling docker with docker run --rm --log-driver=none -v /var/lib/toil/tmp8eKuHh/localTempDir/tchaTvC:/data.
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	WARNING:toil_scripts.batch_alignment.bwa_alignment:Calling docker with docker run --rm --log-driver=none -v /var/lib/toil/tmp8eKuHh/localTempDir/tchaTvC:/data.
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	Calling docker with docker run --rm --log-driver=none -v /var/lib/toil/tmp8eKuHh/localTempDir/tchaTvC:/data
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	WARNING: many programs require read groups. Please specify with -R if you can.
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	[W::stk_mergepe] the 2nd file has fewer records.
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	Traceback (most recent call last):
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	  File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 283, in main
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	    fileStore=fileStore)
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1294, in _execute
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	    returnValues = self.run(fileStore)
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1400, in run
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	  File "toil_scripts/batch_alignment/bwa_alignment.py", line 462, in fix_bam_header
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 652, in readGlobalFile
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	    os.link(cachedAbsFilePath, userPath)
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	OSError: [Errno 1] Operation not permitted
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	Exiting the worker because of a failed jobWrapper on host ip-172-31-28-135
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host ip-172-31-28-135
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job a3b60d83-825c-4e6d-9d41-6a76f2356d12 to 1
INFO:toil.batchSystems.mesos.batchSystem:Preparing to launch Mesos task 17 using offer 2e1d557f-bae2-4d81-8a02-b72a4092d5b8-O796...
INFO:toil.batchSystems.mesos.batchSystem:...launching Mesos task 17
WARNING:toil.leader:The jobWrapper seems to have left a log file, indicating failure: a3b60d83-825c-4e6d-9d41-6a76f2356d12
WARNING:toil.leader:Reporting file: a3b60d83-825c-4e6d-9d41-6a76f2356d12
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	---TOIL WORKER OUTPUT LOG---
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	WARNING:toil_scripts.batch_alignment.bwa_alignment:Calling docker with docker run --rm --log-driver=none -v /var/lib/toil/tmp9ydzAE/localTempDir/t2WImy9:/data.
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	WARNING:toil_scripts.batch_alignment.bwa_alignment:Calling docker with docker run --rm --log-driver=none -v /var/lib/toil/tmp9ydzAE/localTempDir/t2WImy9:/data.
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	Calling docker with docker run --rm --log-driver=none -v /var/lib/toil/tmp9ydzAE/localTempDir/t2WImy9:/data
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	WARNING: many programs require read groups. Please specify with -R if you can.
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	[W::stk_mergepe] the 2nd file has fewer records.
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	Traceback (most recent call last):
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	  File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 283, in main
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	    fileStore=fileStore)
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1294, in _execute
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	    returnValues = self.run(fileStore)
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1400, in run
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	    rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	  File "toil_scripts/batch_alignment/bwa_alignment.py", line 462, in fix_bam_header
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 652, in readGlobalFile
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	    os.link(cachedAbsFilePath, userPath)
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	OSError: [Errno 1] Operation not permitted
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	Exiting the worker because of a failed jobWrapper on host ip-172-31-28-134
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host ip-172-31-28-134
WARNING:toil.leader:a3b60d83-825c-4e6d-9d41-6a76f2356d12:	WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job a3b60d83-825c-4e6d-9d41-6a76f2356d12 to 0
WARNING:toil.leader:Job: a3b60d83-825c-4e6d-9d41-6a76f2356d12 is completely failed
INFO:toil.leader:Only failed jobs and their dependents (1 total) are remaining, so exiting.
```

**Comment by jvivian** [comment] 2016-02-17 21:52
Hey @jpdna ,

I've never seen this and it's a weird place to fail.  At this point, BWA has already run, samtools has already done the conversion, and it's failing when pulling the **aligned.bam** from the jobStore in the **fix_bam_header**.   

R3.8xlarge has 640GB of ephemeral store which automatically gets mapped to /var/lib/toil _unless_ you specify `--ebs-volume-size`, which your'e doing.  Try launching the cluster again without `--ebs-volume-size` and resume your pipeline from the last successful checkpoint by adding `--restart` to the end.  This will save you from having to run the pipeline again assuming your jobstore `aws:us-west-2:paschall-toil-jobstore` still exists.

**Comment by hannes-ucsc** [comment] 2016-02-17 23:11
@jpdna, How hard would it be to run this without EBS? There is a low chance that that might cause it.

Also, @cket is working on https://github.com/BD2KGenomics/toil/issues/686 which will make diagnosing this easier. I'll post-pone the reproduction until that's finished.

**Comment by hannes-ucsc** [comment] 2016-02-17 23:13
... which should be today or early tomorrow.

**Comment by fnothaft** [comment] 2016-02-17 23:23
Also, reproduces as:

```
NING:toil.leader:d4132ddf-2e42-4175-aa61-ffdb026c19a8:       Traceback (most recent call last):
WARNING:toil.leader:d4132ddf-2e42-4175-aa61-ffdb026c19a8:         File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 282, in main
WARNING:toil.leader:d4132ddf-2e42-4175-aa61-ffdb026c19a8:           fileStore=fileStore)
WARNING:toil.leader:d4132ddf-2e42-4175-aa61-ffdb026c19a8:         File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1281, in _execute
WARNING:toil.leader:d4132ddf-2e42-4175-aa61-ffdb026c19a8:           returnValues = self.run(fileStore)
WARNING:toil.leader:d4132ddf-2e42-4175-aa61-ffdb026c19a8:         File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1383, in run
WARNING:toil.leader:d4132ddf-2e42-4175-aa61-ffdb026c19a8:           rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
WARNING:toil.leader:d4132ddf-2e42-4175-aa61-ffdb026c19a8:         File "toil_scripts/batch_alignment/bwa_alignment.py", line 410, in run_bwa
WARNING:toil.leader:d4132ddf-2e42-4175-aa61-ffdb026c19a8:         File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 569, in writeGlobalFile
WARNING:toil.leader:d4132ddf-2e42-4175-aa61-ffdb026c19a8:           os.chmod(absLocalFileName, stat.S_IRUSR | stat.S_IRGRP | stat.S_IROTH)
WARNING:toil.leader:d4132ddf-2e42-4175-aa61-ffdb026c19a8:       OSError: [Errno 1] Operation not permitted: '/var/lib/toil/tmpdbRKrK/localTempDir/tGCntU0/aligned.bam'
```

I'll restart my current cluster without EBS volumes and see if it repros.

**Comment by fnothaft** [comment] 2016-02-18 01:19
This repros for me without EBS volumes.

**Comment by hannes-ucsc** [comment] 2016-02-18 01:42
First thing I notice is that the bwakit wrapper does not fix up the permissions:

https://github.com/BD2KGenomics/cgl-docker-lib/blob/master/bwakit/wrapper.sh

It should look like this:

https://github.com/BD2KGenomics/cgl-docker-lib/blob/master/samtools/wrapper.sh

**Comment by hannes-ucsc** [comment] 2016-02-18 01:49
If the file is world readable then that would explain the non-deterministic aspect to this. It can still be uploaded to the jobstore and will be downloaded on a cache miss but on a cache hit Toil will try to chmod a file owned by root and that will fail.

**Comment by fnothaft** [comment] 2016-02-18 02:13
Ah, fascinating. Good to know. If I made the change to bwakit, could I get a quick merge?

**Comment by fnothaft** [comment] 2016-02-18 02:18
See https://github.com/BD2KGenomics/cgl-docker-lib/pull/83. Can you review/merge @hannes-ucsc ? I will then test on the cluster.

**Comment by fnothaft** [comment] 2016-02-18 02:26
Sorry, but I went to test this and realized that I did it wrong. Can you look at https://github.com/BD2KGenomics/cgl-docker-lib/pull/84?

**Comment by fnothaft** [comment] 2016-02-18 11:22
This seems to be resolved with the latest PR I've opened against cgl-docker-lib and https://github.com/fnothaft/toil-scripts/commit/b5954c047f3699836f9b65d38a6f3ade0c611bcd. @jpdna can you test on your side? Until @hannes-ucsc or @jvivian merge https://github.com/BD2KGenomics/cgl-docker-lib/issues/85, you will need to manually build the images on your cluster.

With this, we make it all the way through ADAM preprocessing, and almost all of the way through GATK preprocessing (our upload to S3 failed because I was missing an import).

**Closed** 2016-02-18 22:56 UTC
Labels: bug
